# Generated by Django 5.0.1 on 2024-06-03 13:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cajero', models.CharField(max_length=100, unique=True)),
                ('descripcion', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Gaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gaveta', models.CharField(max_length=100, unique=True)),
                ('denominacion_billete', models.DecimalField(decimal_places=2, max_digits=10)),
                ('banco', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_actualizacion', models.DateField()),
                ('numero_precinto', models.CharField(max_length=100)),
                ('total_por_denominacion', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero')),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.gaveta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
