# Generated by Django 5.0.1 on 2024-06-16 13:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Banco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Billete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billete_denominacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_gaveta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portavalor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_portavalor', models.CharField(max_length=10, unique=True)),
                ('nombre_portavalor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='RedAtm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('red_atm', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diferencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_gaveta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Cajero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_cajero', models.CharField(max_length=100, unique=True)),
                ('ubicacion', models.CharField(max_length=255)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.banco')),
                ('red_atm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.redatm')),
            ],
        ),
        migrations.CreateModel(
            name='Gaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_gaveta', models.CharField(max_length=10, unique=True)),
                ('banco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.banco')),
                ('cajero', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero')),
                ('denominacion_billete', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.billete')),
                ('modelo_atm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.modelo')),
                ('tipologia', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipologia')),
            ],
        ),
        migrations.CreateModel(
            name='Operacion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_operacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_habilitacion', models.DateField()),
                ('precinto_gaveta', models.CharField(max_length=15, unique=True)),
                ('total_por_gaveta', models.IntegerField(verbose_name='')),
                ('precinto_depurador', models.CharField(blank=True, max_length=15, null=True, unique=True)),
                ('precinto_bolso', models.CharField(max_length=15, unique=True)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero', verbose_name='ATM')),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.gaveta')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Diferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField()),
                ('recorrido', models.IntegerField()),
                ('total_diferencia', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero')),
                ('portavalor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.portavalor')),
                ('tipo_diferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipodiferencia')),
            ],
        ),
    ]
