# Generated by Django 5.0.1 on 2024-06-24 13:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero', verbose_name='ATM'),
        ),
    ]
