# Generated by Django 5.0.1 on 2024-06-24 04:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='cajero',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero', unique=True, verbose_name='ATM'),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='gaveta_2',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaveta_2', to='operaciones.gaveta', unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='gaveta_3',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaveta_3', to='operaciones.gaveta', unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='gaveta_4',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gaveta_4', to='operaciones.gaveta', unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_bolso_2',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_gaveta_2',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_gaveta_3',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_gaveta_4',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_gaveta',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_gaveta_2',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_gaveta_3',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_gaveta_4',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
    ]
