# Generated by Django 5.0.1 on 2024-06-17 16:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='gaveta',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='precinto_gaveta',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='total_por_gaveta',
        ),
        migrations.CreateModel(
            name='DetalleGaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto_gaveta', models.CharField(max_length=15, unique=True)),
                ('total_por_gaveta', models.IntegerField()),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.gaveta')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_gaveta', to='operaciones.operacion')),
            ],
        ),
    ]
