# Generated by Django 5.0.1 on 2024-06-18 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0002_remove_operacion_gaveta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='precinto_bolso',
        ),
        migrations.CreateModel(
            name='PrecintoBolso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precinto_bolso', models.CharField(max_length=15, unique=True)),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='precintos_bolso', to='operaciones.operacion')),
            ],
        ),
    ]
