# Generated by Django 5.0.1 on 2024-06-04 13:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0004_alter_cajero_banco'),
    ]

    operations = [
        migrations.AddField(
            model_name='gaveta',
            name='cajero',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero'),
        ),
        migrations.AlterField(
            model_name='gaveta',
            name='banco',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.banco'),
        ),
        migrations.AlterField(
            model_name='gaveta',
            name='denominacion_billete',
            field=models.DecimalField(decimal_places=0, max_digits=5),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_denominacion',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
