# Generated by Django 5.0.1 on 2024-06-07 13:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0005_gaveta_cajero_alter_gaveta_banco_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Billete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billete_denominacion', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo_gaveta', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Portavalor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_portavalor', models.IntegerField(unique=True)),
                ('nombre_portavalor', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='TipoDiferencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_diferencia', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Tipologia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipologia_gaveta', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='operacion',
            name='numero_precinto',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_denominacion',
            field=models.IntegerField(),
        ),
        migrations.AddField(
            model_name='operacion',
            name='billete',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.billete'),
        ),
        migrations.AlterField(
            model_name='gaveta',
            name='denominacion_billete',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.billete'),
        ),
        migrations.AddField(
            model_name='gaveta',
            name='modelo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.modelo'),
        ),
        migrations.CreateModel(
            name='Diferencias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_actualizacion', models.DateField()),
                ('recorrido', models.IntegerField()),
                ('total_diferencia', models.IntegerField()),
                ('observaciones', models.CharField(max_length=255)),
                ('cajero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.cajero')),
                ('portavalor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.portavalor')),
                ('tipo_diferencia', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipodiferencia')),
            ],
        ),
        migrations.AddField(
            model_name='gaveta',
            name='tipologia',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='operaciones.tipologia'),
        ),
    ]
