# Generated by Django 5.0.1 on 2024-06-07 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0006_billete_modelo_portavalor_tipodiferencia_tipologia_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacion',
            name='numero_precinto',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='portavalor',
            name='id_portavalor',
            field=models.CharField(max_length=10, unique=True),
        ),
    ]
