# Generated by Django 5.0.1 on 2024-06-10 12:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0007_alter_operacion_numero_precinto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gaveta',
            old_name='modelo',
            new_name='modelo_atm',
        ),
    ]
