# Generated by Django 5.0.1 on 2024-06-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0008_rename_modelo_gaveta_modelo_atm'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='billete',
        ),
    ]
