# Generated by Django 5.0.1 on 2024-06-10 13:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0009_remove_operacion_billete'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='total_por_denominacion',
            new_name='total_por_gaveta',
        ),
    ]
