# Generated by Django 5.0.1 on 2024-06-12 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_rename_total_por_denominacion_operacion_total_por_gaveta'),
    ]

    operations = [
        migrations.CreateModel(
            name='DetalleGaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_precinto', models.CharField(max_length=100)),
                ('total_por_gaveta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.gaveta')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_gaveta', to='operaciones.operacion')),
            ],
        ),
    ]
