# Generated by Django 5.0.1 on 2024-06-13 12:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_rename_total_por_denominacion_operacion_total_por_gaveta'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='precinto_bolso',
            field=models.IntegerField(default=5555, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='precinto_depurador',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
