# Generated by Django 5.0.1 on 2024-06-14 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0010_rename_total_por_denominacion_operacion_total_por_gaveta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='numero_precinto',
            new_name='precinto_gaveta',
        ),
    ]
