# Generated by Django 5.0.1 on 2024-06-13 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_operacion_precinto_bolso_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gaveta',
            name='id_gaveta',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='numero_precinto',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_bolso',
            field=models.CharField(max_length=10, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_depurador',
            field=models.CharField(blank=True, max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='total_por_gaveta',
            field=models.CharField(max_length=25),
        ),
    ]
