# Generated by Django 5.0.1 on 2024-06-14 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_rename_numero_precinto_operacion_precinto_gaveta'),
    ]

    operations = [
        migrations.RenameField(
            model_name='operacion',
            old_name='fecha_actualizacion',
            new_name='fecha_habilitacion',
        ),
    ]
