# Generated by Django 5.0.1 on 2024-06-12 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0011_detallegaveta'),
    ]

    operations = [
        migrations.AlterField(
            model_name='detallegaveta',
            name='total_por_gaveta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
    ]
