# Generated by Django 5.0.1 on 2024-06-14 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_alter_gaveta_id_gaveta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacion',
            name='gaveta',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='numero_precinto',
        ),
        migrations.RemoveField(
            model_name='operacion',
            name='total_por_gaveta',
        ),
        migrations.CreateModel(
            name='DetalleGaveta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_precinto', models.CharField(max_length=10, unique=True)),
                ('total_por_gaveta', models.CharField(max_length=25)),
                ('gaveta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='operaciones.gaveta')),
                ('operacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles_gaveta', to='operaciones.operacion')),
            ],
        ),
    ]
