# Generated by Django 5.0.1 on 2024-06-14 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0012_rename_fecha_actualizacion_operacion_fecha_habilitacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacion',
            name='precinto_bolso',
            field=models.CharField(default=9999, max_length=15, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='operacion',
            name='precinto_depurador',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='operacion',
            name='precinto_gaveta',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
