# Generated by Django 5.0.1 on 2024-06-12 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operaciones', '0013_remove_operacion_total_por_gaveta_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gaveta',
            name='id_gaveta',
        ),
        migrations.AlterField(
            model_name='detallegaveta',
            name='total_por_gaveta',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
